#-------------------------#
#                         #
#   NAME:     AREWARDS    #
#   AUTHOR:   DavidML16   #
#                         #
#-------------------------#


# Language of plugin
# Availables by default: EN, ES
Language: EN


# Command name, default: /rewards
# For the changes to take effect, a full server restart is required
Commands:
    Rewards: rewards


# Database details
MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    User: root
    Password: example
    Database: arewards


# Enable/disable if you want cubelet open gui updates in realtime.
LiveGuiUpdates: true


# Enable/disable if you want to be reminded that you have rewards to claim when you login
LoginReminder: false


# Change hologram settings
# Update interval default: 30 (1.5s)
# Color animation default colors: &f and &c
Holograms:
    UpdateInterval: 30
    ColorAnimation:
        - '&f'
        - '&c'