name: ARewards
version: ${project.version}
main: me.davidml16.arewards.Main
softdepend: [HolographicDisplays, ProtocolLib, PlaceholderAPI, Votifier, Multiverse-Core]
authors: [DavidML16]
api-version: 1.13